version: '3.8'

services:
  whatsmiau:
    build: .
    container_name: whatsmiau
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis:6379
      - DB_URL=data.db
    volumes:
      - ./data.db:/app/data.db
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
    driver: local
